# Generated by Django 3.2.6 on 2021-11-24 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(db_index=True, max_length=512, verbose_name='Title')),
                ('slug', models.SlugField(max_length=512, unique=True, verbose_name='Slug')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Is arhive season?')),
            ],
            options={
                'verbose_name': 'season',
                'verbose_name_plural': 'seasons',
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(db_index=True, max_length=512, verbose_name='Title')),
                ('points', models.PositiveIntegerField(verbose_name='Total points')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing', to='main.season', verbose_name='season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'standing',
                'verbose_name_plural': 'standings',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(db_index=True, max_length=512, verbose_name='Title')),
                ('slug', models.SlugField(max_length=512, unique=True, verbose_name='Slug')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='main.season', verbose_name='season')),
            ],
            options={
                'verbose_name': 'stage',
                'verbose_name_plural': 'stages',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(db_index=True, max_length=512, verbose_name='Title')),
                ('slug', models.SlugField(max_length=512, unique=True, verbose_name='Slug')),
                ('result_1', models.PositiveIntegerField(verbose_name='First team score:')),
                ('result_2', models.PositiveIntegerField(verbose_name='Second team score:')),
                ('end_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='This match will start at')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='main.stage', verbose_name='stage')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('forecast_1', models.PositiveIntegerField(verbose_name='Forecast for first team:')),
                ('forecast_2', models.PositiveIntegerField(verbose_name='Forecast for second team:')),
                ('is_X2', models.BooleanField(default=False, verbose_name='Is supermatch?')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='main.match', verbose_name='match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'forecast',
                'verbose_name_plural': 'forecasts',
            },
        ),
    ]
