# Generated by Django 3.2.6 on 2021-12-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standing',
            name='title',
        ),
    ]
