# Generated by Django 3.2.6 on 2021-12-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_seasonstanding_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='forecast_1',
            field=models.PositiveIntegerField(default=0, verbose_name='Forecast for first team:'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='forecast_2',
            field=models.PositiveIntegerField(default=0, verbose_name='Forecast for second team:'),
        ),
        migrations.AlterField(
            model_name='match',
            name='result_1',
            field=models.PositiveIntegerField(default=0, verbose_name='First team score:'),
        ),
        migrations.AlterField(
            model_name='match',
            name='result_2',
            field=models.PositiveIntegerField(default=0, verbose_name='Second team score:'),
        ),
    ]
